image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Only run init if app folder doesn't exist
      if [ ! -d "app" ]; then
        npx react-native init app --version latest --skip-install
        cd app && npm install
      fi
  - command: |
      cd app
      npm start
ports:
  - port: 8081
    onOpen: open-preview
